atoms:
  -
    id: assets-2745
    type: assets
    title: 'Custom CSS / JS'
    attributes:
      enabled: '0'
      css:
        - { location: 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css', inline: '', extra: {  }, priority: '0', name: 'Bootstrap css' }
      javascript:
        - { location: 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js', inline: '', in_footer: '0', extra: {  }, priority: '0', name: 'Bootstrap js' }
